apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: selfie-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: selfie-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/post_selfie
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /onboarding/post_selfie
