include:
- ./func/*
kind: ArchiveUploadSpec
name: func-NRam

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: selfie-fn-4504a06d-6767-415f-9c21-e9a5fb595e81
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: selfie-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-NRam
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-25T20:16:07Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: selfie-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: selfie-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.selfie
    packageref:
      name: selfie-fn-4504a06d-6767-415f-9c21-e9a5fb595e81
      namespace: default
  requestsPerPod: 10000
  resources: {}
